import { PAGE_PATH } from "./page-path";

export const PRIVATE_ROUTES = [
	PAGE_PATH.DASHBOARD,
	PAGE_PATH.TASKS,
	PAGE_PATH.CHILDREN,
];

export const PUBLIC_ROUTES = [PAGE_PATH.AUTH, PAGE_PATH.SIGNUP];
